### ISSUE TITLE
The latest version 0.6.0 contains non-ES5 code

### ISSUE THREAD

**Issue by josdejong** [epoberezkin/json-source-map#4]
When using the latest version of `json-source-map` in a project of mine, I can no longer minify my own project (using uglifyjs), I get the following error:

```
SyntaxError: Unexpected token: name «of», expected: punc «;»
```
This is because the published code of `json-source-map` contains non-ES5 code, it uses `of`:

https://github.com/epoberezkin/json-source-map/blob/86c7024ea3f906b0c5c56a31309bb485ee73b6a7/index.js#L370

is this intentional or accidental?

**Comment by epoberezkin** [comment]
This code will never execute in ES5 environment, but it won't parse with ES5 parsers indeed... This iterator should be just iterated manually then - I will update.

**Comment by josdejong** [comment]
thanks!

**Comment by epoberezkin** [comment]
it's in 0.6.1

**Comment by josdejong** [comment]
:+1:
